<?php

namespace AppBundle\Repository;

/**
 * ChienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChienRepository extends \Doctrine\ORM\EntityRepository
{
}
